service: evergarden
frameworkVersion: '2'
configValidationMode: error
variablesResolutionMode: 20210326
useDotenv: true

plugins:
  - serverless-python-requirements

custom:
  name: evergarden
  pythonRequirements:
    dockerizePip: non-linux
    usePoetry: true

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: ${env:AWS_REGION}
  stage: ${opt:stage, 'dev'}
  memorySize: ${env:MEMORY_SIZE}
  timeout: ${env:TIMEOUT}
  apiName: ${env:API_NAME}

package:
  patterns:
    - evergarden/**
    # documents
    - '*.md'
    # dot files
    - '.DS_Store'
    - '.envrc'
    - 'setup.cfg'
    - '.pre-commit-config.yaml'
    - '.npmignore'
    # useless
    - 'package-lock.json'
    - 'package.json'
    - 'Makefile'
    # directories
    - '.idea/**'
    - '.mypy_cache/**'
    - '!.git/**'
    - '!node_modules/**'

functions:
  evergarden-api:
    name: evergarden-api-${self:provider.stage}
    handler: evergarden.main.handler
    events:
      - httpApi:
          path: '*'
